# Generated by Django 3.1.7 on 2021-05-07 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('score', models.FloatField(blank=True, default=0, verbose_name='score')),
                ('run_count', models.IntegerField(blank=True, default=0, verbose_name='run_count')),
                ('num_participants', models.IntegerField(blank=True, default=0, verbose_name='num_participants')),
                ('sum_duration', models.FloatField(blank=True, default=0, verbose_name='sum_duration')),
                ('sum_distance_walk', models.FloatField(blank=True, default=0, verbose_name='sum_distance_walk')),
                ('sum_distance_run', models.FloatField(blank=True, default=0, verbose_name='sum_distance_run')),
                ('sum_distance_bike', models.FloatField(blank=True, default=0, verbose_name='sum_distance_bike')),
                ('sum_distance_ebike', models.FloatField(blank=True, default=0, verbose_name='sum_distance_ebike')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile')),
            ],
        ),
    ]
