# Generated by Django 4.0.2 on 2022-02-28 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('route', '__first__'),
        ('user', '__first__'),
        ('group', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='StravaRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, default='unbekannt', max_length=300, verbose_name='creator')),
                ('strava_handle', models.PositiveBigIntegerField(blank=None, unique=True, verbose_name='strava_handle')),
                ('profile_handle', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='profile_handle')),
                ('route_handle', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='route_handle')),
                ('distance', models.FloatField(verbose_name='distance')),
                ('elevation_gain', models.FloatField(blank=True, default=0, verbose_name='elevation_gain')),
                ('time_start', models.DateTimeField(verbose_name='time_start')),
                ('duration', models.DurationField(verbose_name='duration')),
                ('type', models.CharField(choices=[('WALK', 'Gehen'), ('RUN', 'Laufen'), ('BIKE', 'Rad'), ('E-BIKE', 'E-Bike')], default='RUN', max_length=50, verbose_name='type')),
                ('note', models.CharField(blank=True, max_length=2000, null=True, verbose_name='note')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(verbose_name='distance')),
                ('elevation_gain', models.FloatField(blank=True, default=0, verbose_name='elevation_gain')),
                ('time_start', models.DateTimeField(verbose_name='time_start')),
                ('duration', models.DurationField(verbose_name='duration')),
                ('type', models.CharField(choices=[('WALK', 'Gehen'), ('RUN', 'Laufen'), ('BIKE', 'Rad'), ('E-BIKE', 'E-Bike')], default=(('WALK', 'Gehen'), ('RUN', 'Laufen'), ('BIKE', 'Rad'), ('E-BIKE', 'E-Bike')), max_length=50, verbose_name='type')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.group')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='route.route')),
            ],
        ),
    ]
