# Generated by Django 4.0.2 on 2022-02-28 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateField(auto_now=True, verbose_name='joined')),
                ('name', models.CharField(default='', max_length=200, verbose_name='name')),
                ('confirmed', models.BooleanField(default=False, verbose_name='confirmed')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('role', models.CharField(choices=[('Nutzer', 'Nutzer'), ('Trainer', 'Trainer'), ('Vorstand', 'Vorstand'), ('Administator', 'Administator')], default='Nutzer', max_length=200, verbose_name='role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
